services:
  postgres:
    image: 'postgres:18.1'
    environment:
      - 'POSTGRES_DB=spring_ai_examples'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
  qdrant:
    image: 'qdrant/qdrant:v1.16.3'
    ports:
      - '6334'
